/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\assets\autocabinet.glb 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera, OrthographicCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/autocabinet.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.025}>
        <group position={[0, 8.375, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, -0.13, 0]}>
            <mesh geometry={nodes.EMBLEM_1.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_2.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_3.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_4.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_5.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_6.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_7.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_8.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_9.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_10.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_11.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_12.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_13.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_14.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_15.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_16.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_17.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_18.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_19.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_20.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_21.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_22.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_23.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_24.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_25.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_26.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_27.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_28.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_29.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_30.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_31.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_32.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_33.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_34.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_35.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_36.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_37.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_38.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_39.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_40.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_41.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_42.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_43.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_44.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_45.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_46.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_47.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_48.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_49.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_50.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_51.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_52.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_53.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_54.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_55.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_56.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_57.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_58.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_59.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_60.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_61.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_62.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_63.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_64.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_65.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_66.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_67.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_68.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_69.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_70.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_71.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_72.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_73.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_74.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_75.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_76.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_77.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_78.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_79.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_80.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_81.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_82.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_83.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_84.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_85.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_86.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_87.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_88.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_89.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_90.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_91.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_92.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_93.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_94.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_95.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_96.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_97.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_98.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_99.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_100.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_101.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_102.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_103.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_104.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_105.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_106.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_107.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_108.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_109.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_110.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_111.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_112.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_113.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_114.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_115.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_116.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_117.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_118.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_119.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_120.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_121.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_122.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_123.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_124.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_125.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_126.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_127.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_128.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_129.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_130.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_131.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_132.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_133.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_134.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_135.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_136.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_137.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_138.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_139.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_140.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_141.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_142.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_143.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_144.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_145.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_146.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_147.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_148.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_149.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_150.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_151.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_152.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_153.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_154.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_155.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_156.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_157.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_158.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_159.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_160.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_161.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_162.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_163.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_164.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_165.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_166.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_167.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_168.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_169.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_170.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_171.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_172.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_173.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_174.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_175.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_176.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_177.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_178.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_179.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_180.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_181.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_182.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_183.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_184.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_185.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_186.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_187.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_188.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_189.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_190.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_191.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_192.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_193.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_194.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_195.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_196.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_197.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_198.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_199.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_200.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_201.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_202.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_203.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_204.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_205.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_206.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_207.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_208.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_209.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_210.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_211.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_212.geometry} material={materials['Platinum Polished #1']} />
            <mesh geometry={nodes.EMBLEM_213.geometry} material={materials['Platinum Polished #1']} />
          </group>
          <mesh geometry={nodes.ALCOHOL_LIFT_1.geometry} material={materials['ALCOHOL LIFT:0:0:0']} />
          <mesh geometry={nodes.ALCOHOL_LIFT_2.geometry} material={materials['ALCOHOL LIFT:0:0:0']} />
          <mesh geometry={nodes.ALCOHOL_LIFT_3.geometry} material={materials['ALCOHOL LIFT:0:0:0']} />
          <mesh geometry={nodes.ALCOHOL_LIFT_4.geometry} material={materials['ALCOHOL LIFT:0:0:0']} />
          <mesh geometry={nodes.ALCOHOL_LIFT_5.geometry} material={materials['ALCOHOL LIFT:0:0:0']} />
          <mesh geometry={nodes.ALCOHOL_LIFT_6.geometry} material={materials['ALCOHOL LIFT:0:0:0']} />
          <mesh geometry={nodes.ALCOHOL_LIFT_7.geometry} material={materials['ALCOHOL LIFT:0:0:0']} />
          <mesh geometry={nodes.ALCOHOL_LIFT_8.geometry} material={materials['ALCOHOL LIFT:0:0:0']} />
          <mesh geometry={nodes.ALCOHOL_LIFT_9.geometry} material={materials['ALCOHOL LIFT:0:0:0']} />
          <mesh geometry={nodes.ALCOHOL_LIFT_10.geometry} material={materials['ALCOHOL LIFT:0:0:0']} />
          <mesh geometry={nodes.ALCOHOL_LIFT_11.geometry} material={materials['ALCOHOL LIFT:0:0:0']} />
          <mesh geometry={nodes.ALCOHOL_LIFT_12.geometry} material={materials['ALCOHOL LIFT:0:0:0']} />
          <mesh geometry={nodes.ALCOHOL_LIFT_13.geometry} material={materials['ALCOHOL LIFT:0:0:0']} />
          <mesh geometry={nodes.ALCOHOL_LIFT_14.geometry} material={materials['ALCOHOL LIFT:0:0:0']} />
          <mesh geometry={nodes.OUTER_1.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_2.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_3.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_4.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_5.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_6.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_7.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_8.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_9.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_10.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_11.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_12.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_13.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_14.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_15.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_16.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_17.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_18.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_19.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_20.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_21.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_22.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_23.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_24.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_25.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.OUTER_26.geometry} material={materials['Paint Gloss Black #1']} />
          <mesh geometry={nodes.LINER_1.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_2.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_3.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_4.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_5.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_6.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_7.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_8.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_9.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_10.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_11.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_12.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_13.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_14.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_15.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_16.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_17.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_18.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_19.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_20.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_21.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_22.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_23.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_24.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_25.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_26.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_27.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_28.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_29.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_30.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_31.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_32.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_33.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_34.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_35.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_36.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_37.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.LINER_38.geometry} material={materials['Platinum Polished #1']} />
          <mesh geometry={nodes.COGNAC_CUPS_1.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.COGNAC_CUPS_2.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.COGNAC_2.geometry} material={materials['Liquid Chardonnay']} />
          <mesh geometry={nodes.BOTTLES_1.geometry} material={materials.wire_214228153} />
          <mesh geometry={nodes.CAP_6.geometry} material={materials['Metal Polished Red']} />
          <mesh geometry={nodes.BOTTLE_6.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.LIQUID_4.geometry} material={materials['Liquid Chardonnay']} />
          <mesh geometry={nodes.LIQUID_5.geometry} material={materials['Liquid Water #1']} />
          <mesh geometry={nodes.BOTTLE_7.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.CAP_7.geometry} material={materials['Gold 24k Polished #1']} />
          <mesh geometry={nodes.BOTTLE_8.geometry} material={materials['Glass (Solid) Yellow']} />
          <mesh geometry={nodes.CAP_8.geometry} material={materials['Copper Polished']} />
          <mesh geometry={nodes.LIQUID_6.geometry} material={materials.wire_225198087} />
          <mesh geometry={nodes.LIQUID_7.geometry} material={materials['Liquid Chardonnay #1']} />
          <mesh geometry={nodes.BOTTLE_9.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.CAP_9.geometry} material={materials['Anodized Titanium Brushed Purple']} />
          <mesh geometry={nodes.BOTTLE_10.geometry} material={materials['Glass (Solid) Red']} />
          <mesh geometry={nodes.CAP_10.geometry} material={materials['Soft Textured Red #1']} />
          <mesh geometry={nodes.BOTTLE_11.geometry} material={materials['Anodized Titanium Polished Pink']} />
          <mesh geometry={nodes.BOTTLE_12.geometry} material={materials['Anodized Titanium Polished Pink']} />
          <mesh geometry={nodes.CAP_11.geometry} material={materials['Anodized Titanium Rough Pink']} />
          <mesh geometry={nodes.CAP_12.geometry} material={materials['Anodized Titanium Rough Pink']} />
          <mesh geometry={nodes.TOP_SHELL_1.geometry} material={materials['TOP SHELL:0:0:0']} />
          <mesh geometry={nodes.TOP_SHELL_2.geometry} material={materials['TOP SHELL:0:0:0']} />
          <mesh geometry={nodes.TOP_SHELL_3.geometry} material={materials['TOP SHELL:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_1.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_2.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_3.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_4.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_5.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_6.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_7.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_8.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_9.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_10.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_11.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_12.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_13.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_14.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_15.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_16.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_17.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_18.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_19.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_20.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_21.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_22.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_23.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_24.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_25.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_26.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_27.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_28.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_29.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_30.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_31.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_32.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_33.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_34.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.LIQUOR_LIFT_35.geometry} material={materials['LIQUOR LIFT:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_1.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_2.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_3.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_4.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_5.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_6.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_7.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_8.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_9.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_10.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_11.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_12.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_13.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_14.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_15.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_16.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_17.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_18.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_19.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_20.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_21.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_22.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_23.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_24.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_25.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_26.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_27.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_28.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.BOTTOM_BRACKET_29.geometry} material={materials['BOTTOM BRACKET:0:0:0']} />
          <mesh geometry={nodes.DRAWER_1.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_2.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_3.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_4.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_5.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_6.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_7.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_8.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_9.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_10.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_11.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_12.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_13.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_14.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_15.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_16.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_17.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_18.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_19.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_20.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_21.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_22.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_23.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_24.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_25.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_26.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_27.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_28.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_29.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_30.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_31.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_32.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_33.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_34.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_35.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_36.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.DRAWER_37.geometry} material={materials['DRAWER:0:0:0']} />
          <mesh geometry={nodes.FREEZER_LINER_1.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_2.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_3.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_4.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_5.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_6.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_7.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_8.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_9.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_10.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_11.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_12.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_13.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_14.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_15.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_16.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_17.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_18.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_19.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_20.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_21.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_22.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_23.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_24.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_25.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_26.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_27.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_28.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_29.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_30.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_31.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_32.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_33.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_34.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.FREEZER_LINER_35.geometry} material={materials['Aluminum Rough']} />
          <mesh geometry={nodes.CUP_MAT_1.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.WHISKY_GLASS_1.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.WHISKY_GLASS_2.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.WHISKY_GLASS_3.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.VODKA_GLASS_1.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.VODKA_GLASS_2.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.VODKA_GLASS_3.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.SHOT_GLASS_1.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.SHOT_GLASS_2.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.SHOT_GLASS_3.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.SHOT_GLASS_4.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.ICE_TRAY_1.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_2.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_3.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_4.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_5.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_6.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_7.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_8.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_9.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_10.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_11.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_12.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_13.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_14.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_15.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_16.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_17.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_18.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_19.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_20.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_21.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_22.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_23.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_24.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_25.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_26.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_27.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_28.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_29.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_30.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_31.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_32.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_33.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_34.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_35.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_36.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_37.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_38.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_39.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_40.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_41.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_42.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_43.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_TRAY_44.geometry} material={materials['Soft Rough White']} />
          <mesh geometry={nodes.ICE_IN_TRAY_1.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.ICE_IN_TRAY_2.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.ICE_IN_TRAY_3.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.ICE_IN_TRAY_4.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.ICE_IN_TRAY_5.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.ICE_IN_TRAY_6.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.ICE_IN_TRAY_7.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.ICE_IN_TRAY_8.geometry} material={materials['Glass (Solid) White']} />
          <mesh geometry={nodes.GEAR_TRACK_1.geometry} material={materials['Iron Polished']} />
          <mesh geometry={nodes.GEAR_TRACK_2.geometry} material={materials['Iron Polished']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_1.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_2.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_3.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_4.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_5.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_6.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_7.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_8.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_9.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_10.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_11.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_12.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_13.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_14.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_15.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_16.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_17.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_18.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_19.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_20.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_21.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_22.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_23.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_24.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_25.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_26.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_27.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_28.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_29.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_30.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_31.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_32.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_33.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_34.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_35.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_36.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_37.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_38.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_39.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_40.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_41.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_42.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_43.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_44.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_45.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_46.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_47.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_48.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_49.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_50.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_51.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_52.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_53.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_54.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_55.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_56.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_57.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_58.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_59.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_60.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_61.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_62.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_63.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_64.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_65.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_66.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_67.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_68.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_69.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_70.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_71.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_72.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_73.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_74.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_75.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_76.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_77.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_78.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_79.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_80.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_81.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_82.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_83.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_84.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_85.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_86.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_87.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_88.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_89.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_90.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_91.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_92.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_93.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.STEPMOTOR_THREADED_PIPE_94.geometry} material={materials['STEPMOTOR THREADED PIPE:0:0:0']} />
          <mesh geometry={nodes.BASE_1.geometry} material={materials['BASE:0:0:0']} />
          <mesh geometry={nodes.BASE_2.geometry} material={materials['BASE:0:0:0']} />
          <mesh geometry={nodes.BASE_3.geometry} material={materials['BASE:0:0:0']} />
          <mesh geometry={nodes.BASE_4.geometry} material={materials['BASE:0:0:0']} />
          <mesh geometry={nodes.BASE_5.geometry} material={materials['BASE:0:0:0']} />
          <mesh geometry={nodes.BASE_6.geometry} material={materials['BASE:0:0:0']} />
          <mesh geometry={nodes.BASE_7.geometry} material={materials['BASE:0:0:0']} />
          <mesh geometry={nodes.BASE_8.geometry} material={materials['BASE:0:0:0']} />
          <mesh geometry={nodes.BASE_9.geometry} material={materials['BASE:0:0:0']} />
          <mesh geometry={nodes.BASE_10.geometry} material={materials['BASE:0:0:0']} />
          <mesh geometry={nodes.BASE_11.geometry} material={materials['BASE:0:0:0']} />
          <mesh geometry={nodes.BASE_12.geometry} material={materials['BASE:0:0:0']} />
          <mesh geometry={nodes.BASE_13.geometry} material={materials['BASE:0:0:0']} />
        </group>
      </group>
      <PerspectiveCamera makeDefault={false} far={143.943} near={103.703} fov={39.598} position={[-0.104, 0.943, -3.12]} rotation={[-2.992, -0.035, -3.139]} scale={0.025} />
      <PerspectiveCamera makeDefault={false} far={143.943} near={103.703} fov={39.598} position={[-0.104, 0.943, -3.12]} rotation={[-2.992, -0.035, -3.139]} scale={0.025} />
      <OrthographicCamera makeDefault={false} far={90.747} near={48.566} position={[1.105, 2.305, -0.108]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <OrthographicCamera makeDefault={false} far={99.059} near={65.873} position={[0.163, 0.45, 2.092]} scale={0.025} />
      <OrthographicCamera makeDefault={false} far={268.342} near={235.344} position={[6.397, 0.263, -0.475]} rotation={[0, Math.PI / 2, 0]} scale={0.025} />
    </group>
  )
}

useGLTF.preload('/autocabinet.glb')
